gradebook/urls.py
from django.urls import path

from . import views

app_name = 'gradebook'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('groups', views.groups, name='groups'),
    path('groups/<int:groupId>/', views.group, name='group'),
    path('students/<int:studentId>', views.student, name='student'),
    path('groups/add', views.addGroup, name='addGroup'),
    path('students/add', views.addStudent, name='addStudent'),
    path('groups/students/add', views.addStudentToGroup, name='addStudentToGroup'),
    path('groups/grades', views.addGradesForm, name='addGradesForm'),
    path('groups/grades/add', views.addGradesInGroup, name='addGradesInGroup'),
    path('students/grades/add', views.addGrade, name='addGrade'),
    path('students/grades/change', views.changeGrade, name='changeGrade'),
]

python_projekt3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('gradebook/', include('gradebook.urls')),
    path('admin/', admin.site.urls),
]

gradebook/models.py
from django.db import models
from datetime import datetime

class Grade(models.Model):
    value = models.IntegerField(default=2)
    date = models.DateTimeField(default=datetime.now)

class Student(models.Model):
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    grades = models.ManyToManyField(Grade)

class Group(models.Model):
    name = models.CharField(max_length=100)
    students = models.ManyToManyField(Student)

gradebook/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Group, Student, Grade

def dashboard(request):
    groups = Group.objects.all()
    students = Student.objects.all()

    return render(request, 'gradebook/dashboard.html', {'groups': groups, 'students': students})

def groups(request):
    groups = Group.objects.all()
    return render(request, 'gradebook/groups.html', {'groups': groups})

def group(request, groupId):
    group = get_object_or_404(Group, pk=groupId)
    return render(request, 'gradebook/group.html', {'group': group})

def student(request, studentId):
    print(studentId)
    
    currentStudent = get_object_or_404(Student, pk=studentId)
    groups = Group.objects.all()

    for group in groups:
        for student in group.students.all():
            if student.id == currentStudent.id:
                groupId = group.id

    return render(request, 'gradebook/student.html', {'student': currentStudent, 'group': groupId})

def addGroup(request):
    name = request.POST['name']

    group = Group(name=name)
    group.save()

    return redirect('gradebook:dashboard')

def addStudentToGroup(request):
    groupId = request.POST['group']
    studentId = request.POST['student']

    group = get_object_or_404(Group, pk=groupId)
    student = get_object_or_404(Student, pk=studentId)

    if student not in group.students.all():
        group.students.add(student)
        group.save()

    return redirect('gradebook:dashboard')

def addStudent(request):
    firstName = request.POST['firstName']
    lastName = request.POST['lastName']

    student = Student(firstName=firstName, lastName=lastName)
    student.save()
    
    return redirect('gradebook:dashboard')

def addGradesForm(request):
    groupId = request.POST['group']
    group = get_object_or_404(Group, pk=groupId)

    return render(request, 'gradebook/addgrades.html', {'group': group})

def addGradesInGroup(request):
    groupId = request.POST['group']

    for key, value in request.POST.items():
        if key.startswith('grade'):
            studentId = int(key[5:])
            student = Student.objects.get(pk=studentId)
            grade = Grade(value=int(value))
            grade.save()
            student.grades.add(grade)
            student.save()

    return redirect('gradebook:group', groupId)

def addGrade(request):
    studentId = request.POST['student']
    value = request.POST['grade']

    student = get_object_or_404(Student, pk=studentId)
    grade = Grade(value=int(value))
    grade.save()
    student.grades.add(grade)
    student.save()

    return redirect('gradebook:student', studentId)

def changeGrade(request):
    studentId = request.POST['student']
    oldGrade = int(request.POST['grade'])
    newGrade = request.POST['newGrade']

    student = get_object_or_404(Student, pk=studentId)

    for grade in student.grades.all():
        if grade.id == oldGrade:
            grade.value = newGrade
            grade.save()
    
    student.save()

    return redirect('gradebook:student', studentId)

gradebook/templates/gradebook/addgrades.html
<a href="{% url 'gradebook:groups' %}">Back to group</a>
<br />

<h1>Add grades in group</h1>
{% if group.students.all %}
<p>Students:</p>
    <form action="{% url 'gradebook:addGradesInGroup' %}" method="post">
    {% csrf_token %}
        <ul>
        {% for student in group.students.all %}
            <li>
                {{ student.firstName }} {{ student.lastName }}
                <input type="number" name="grade{{ student.id }}" placeholder="Grade" />
            </li>
        {% endfor %}
        </ul>
        <input type="hidden" name="group" value="{{ group.id }}" />
        <input type="submit" value="Add" />
    </form>
{% else %}
    <p>This group is empty.</p>
{% endif %}

gradebook/templates/gradebook/dashboard.html
<h1>Dashboard</h1>
<a href="{% url 'gradebook:groups' %}">Show a list of all groups</a>
<br />
<h2>Add student</h2>
<form action="{% url 'gradebook:addStudent' %}" method="post">
    {% csrf_token %}
    <input type="text" name="firstName" placeholder="First name" />
    <input type="text" name="lastName" placeholder="Last name" />
    <input type="submit" value="Add" />
</form>

<h2>Add group</h2>
<form action="{% url 'gradebook:addGroup' %}" method="post">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Name" />
    <input type="submit" value="Add" />
</form>

{% if groups and students %}
<h2>Add student to group</h2>
<form action="{% url 'gradebook:addStudentToGroup' %}" method="post">
    {% csrf_token %}
    <select name="group">
        {% for group in groups %}
        <option value="{{ group.id }}">{{ group.name }}</option>
        {% endfor %}
    </select>
    <select name="student">
        {% for student in students %}
        <option value="{{ student.id }}">{{ student.firstName }} {{ student.lastName }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Add" />
</form>
{% endif %}

gradebook/templates/gradebook/group.html
<a href="{% url 'gradebook:groups' %}">Back to groups list</a>
<br />

<h1>{{ group.name }}</h1>
{% if group.students.all %}
    <p>Students:</p>
    <ul>
    {% for student in group.students.all %}
        <li><a href="{% url 'gradebook:student' student.id %}">{{ student.firstName }} {{ student.lastName }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>This group is empty.</p>
{% endif %}

gradebook/templates/gradebook/groups.html
<a href="{% url 'gradebook:dashboard' %}">Back to dashboard</a>
<br />

<h1>Groups list</h1>
{% if groups %}
    <ul>
    {% for group in groups %}
        <li><a href="{% url 'gradebook:group' group.id %}">{{ group.name }}</a></li>
    {% endfor %}
    </ul>
    <h2>Add many grades</h2>
    <form action="{% url 'gradebook:addGradesForm' %}" method="post">
            {% csrf_token %}
            <label>Choose group:</label>
            <select name="group">
                {% for group in groups %}
                <option value="{{ group.id }}">{{ group.name }}</option>
                {% endfor %}
            </select>
            <input type="submit" value="Add" />
        </form>
{% else %}
    <p>No groups are available.</p>
{% endif %}

gradebook/templates/gradebook/student.html
<a href="{% url 'gradebook:group' group %}">Back to group</a>
<br />

<h1>{{ student.firstName }} {{ student.lastName }}</h1>

<h2>Grades</h2>
{% if student.grades.all %}
    <ul>
    {% for grade in student.grades.all %}
        <li>{{ grade.value }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>This student has no grades.</p>
{% endif %}

<h2>Add grade</h2>
<form action="{% url 'gradebook:addGrade' %}" method="post">
    {% csrf_token %}
    <input type="text" name="grade" placeholder="Grade" />
    <input type="hidden" name="student" value="{{ student.id }}" />
    <input type="submit" value="Add" />
</form>

{% if student.grades.all %}
<h2>Change grade</h2>
<form action="{% url 'gradebook:changeGrade' %}" method="post">
    {% csrf_token %}
    <select name="grade">
        {% for grade in student.grades.all %}
        <option value="{{ grade.id }}">{{ grade.value }}</option>
        {% endfor %}
    </select>
    <input type="text" name="newGrade" placeholder="New grade" />
    <input type="hidden" name="student" value="{{ student.id }}" />
    <input type="submit" value="Change" />
</form>
{% endif %}